# Generated by Django 5.2.6 on 2025-09-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_created_at_alter_userprofile_answers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="ethics",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="red_lines",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mbti_type",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
