# Generated by Django 5.2.6 on 2025-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_userprofile_ethics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="relationship_duration",
            field=models.CharField(default="0 روز", max_length=50),
        ),
    ]
