# Generated by Django 5.2.6 on 2025-09-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_userprofile_relationship_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="relationship_duration",
            field=models.IntegerField(default=0),
        ),
    ]
